---
driver:
  name: docker_cli
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
  - name: centos-6
    driver_config:
      image: centos:6

suites:
  - name: default
    run_list:
      - recipe[docker-compose::default]
    attributes:
      docker-compose:
        configs:
          - name: "base"
            value:
              base:
                image: "ubuntu:12.04"
                ports:
                  - "8022:22"
