---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[docker-compose::default]
    attributes:
      docker-compose:
        configs:
          - name: "base"
            value:
              base:
                image: "ubuntu:12.04"
                ports:
                  - "8022:22"
